# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Skill

# Model Form Field configuration
form: $/ahoy/pyrolancer/models/skill/fields.yaml

# Model Class name
modelClass: Ahoy\Pyrolancer\Models\Skill

# Default redirect location
defaultRedirect: ahoy/pyrolancer/skills

# Create page
create:
    title: Create Skills
    redirect: ahoy/pyrolancer/skills/update/:id
    redirectClose: ahoy/pyrolancer/skills

# Update page
update:
    title: Edit Skills
    redirect: ahoy/pyrolancer/skills
    redirectClose: ahoy/pyrolancer/skills
