# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: @/plugins/responsiv/pyrolancer/models/category/fields.yaml

# Model Class name
modelClass: Responsiv\Pyrolancer\Models\Category

# Default redirect location
defaultRedirect: responsiv/pyrolancer/categories

# Create page
create:
    title: Create Categories
    redirect: responsiv/pyrolancer/categories/update/:id
    redirectClose: responsiv/pyrolancer/categories

# Update page
update:
    title: Edit Categories
    redirect: responsiv/pyrolancer/categories
    redirectClose: responsiv/pyrolancer/categories

# Preview page
preview:
    title: Preview Categories