# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: ~/plugins/ahoy/pyrolancer/models/projectcategory/fields.yaml

# Model Class name
modelClass: Ahoy\Pyrolancer\Models\ProjectCategory

# Default redirect location
defaultRedirect: ahoy/pyrolancer/projectcategories

# Create page
create:
    title: Create Categories
    redirect: ahoy/pyrolancer/projectcategories/update/:id
    redirectClose: ahoy/pyrolancer/projectcategories

# Update page
update:
    title: Edit Categories
    redirect: ahoy/pyrolancer/projectcategories
    redirectClose: ahoy/pyrolancer/projectcategories

# Preview page
preview:
    title: Preview Categories