# ===================================
#  Relation Behavior Config
# ===================================

skills:
    label: Skills
    list: ~/plugins/ahoy/pyrolancer/models/skill/columns.yaml
    form: ~/plugins/ahoy/pyrolancer/models/skill/fields.yaml

    view:
        showSearch: true

    manage:
        recordsPerPage: 10
        showSearch: true