# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Freelancer

# Model Form Field configuration
form: @/plugins/responsiv/pyrolancer/models/freelancer/fields.yaml

# Model Class name
modelClass: Responsiv\Pyrolancer\Models\Freelancer

# Default redirect location
defaultRedirect: responsiv/pyrolancer/freelancers

# Create page
create:
    title: Create Freelancers
    redirect: responsiv/pyrolancer/freelancers/update/:id
    redirectClose: responsiv/pyrolancer/freelancers

# Update page
update:
    title: Edit Freelancers
    redirect: responsiv/pyrolancer/freelancers
    redirectClose: responsiv/pyrolancer/freelancers

# Preview page
preview:
    title: Preview Freelancers