# ===================================
#  Relation Behavior Config
# ===================================

items:
    label: Item
    list: ~/plugins/ahoy/pyrolancer/models/portfolioitem/columns.yaml
    form: ~/plugins/ahoy/pyrolancer/models/portfolioitem/fields.yaml
    view:
        toolbarButtons: create|delete
    manage:
        showSearch: true
        recordsPerPage: 10
