# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Portfolio

# Model Form Field configuration
form: $/ahoy/pyrolancer/models/portfolio/fields.yaml

# Model Class name
modelClass: Ahoy\Pyrolancer\Models\Portfolio

# Default redirect location
defaultRedirect: ahoy/pyrolancer/portfolios

# Create page
create:
    title: Create Portfolio
    redirect: ahoy/pyrolancer/portfolios/update/:id
    redirectClose: ahoy/pyrolancer/portfolios

# Update page
update:
    title: Edit Portfolio
    redirect: ahoy/pyrolancer/portfolios
    redirectClose: ahoy/pyrolancer/portfolios

# Preview page
preview:
    title: Preview Portfolio