# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: SkillCategory

# Model Form Field configuration
form: @/plugins/responsiv/pyrolancer/models/skillcategory/fields.yaml

# Model Class name
modelClass: Responsiv\Pyrolancer\Models\SkillCategory

# Default redirect location
defaultRedirect: responsiv/pyrolancer/skillcategories

# Create page
create:
    title: Create SkillCategories
    redirect: responsiv/pyrolancer/skillcategories/update/:id
    redirectClose: responsiv/pyrolancer/skillcategories

# Update page
update:
    title: Edit SkillCategories
    redirect: responsiv/pyrolancer/skillcategories
    redirectClose: responsiv/pyrolancer/skillcategories

# Preview page
preview:
    title: Preview SkillCategories