# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Skill Category

# Model Form Field configuration
form: @/plugins/ahoy/pyrolancer/models/skillcategory/fields.yaml

# Model Class name
modelClass: Ahoy\Pyrolancer\Models\SkillCategory

# Default redirect location
defaultRedirect: ahoy/pyrolancer/skillcategories

# Create page
create:
    title: Create Skill Category
    redirect: ahoy/pyrolancer/skillcategories/update/:id
    redirectClose: ahoy/pyrolancer/skillcategories

# Update page
update:
    title: Edit Skill Category
    redirect: ahoy/pyrolancer/skillcategories
    redirectClose: ahoy/pyrolancer/skillcategories

# Preview page
preview:
    title: Preview Skill Category