# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Worker

# Model Form Field configuration
form: ~/plugins/ahoy/pyrolancer/models/worker/fields.yaml

# Model Class name
modelClass: Ahoy\Pyrolancer\Models\Worker

# Default redirect location
defaultRedirect: ahoy/pyrolancer/workers

# Create page
create:
    title: Create Worker
    redirect: ahoy/pyrolancer/workers/preview/:id
    redirectClose: ahoy/pyrolancer/workers/preview/:id

# Update page
update:
    title: Edit Worker
    redirect: ahoy/pyrolancer/workers/preview/:id
    redirectClose: ahoy/pyrolancer/workers/preview/:id

# Preview page
preview:
    title: Preview Worker