# ===================================
#  Relation Behavior Config
# ===================================

skills:
    label: Skills
    list: ~/plugins/ahoy/pyrolancer/models/skill/columns.yaml
    form: ~/plugins/ahoy/pyrolancer/models/skill/fields.yaml
    manage:
        showSearch: true
        recordsPerPage: 10
