# ===================================
#  Relation Behavior Config
# ===================================

bids:
    label: Bid
    list: ~/plugins/ahoy/pyrolancer/models/projectbid/columns.yaml
    form: ~/plugins/ahoy/pyrolancer/models/projectbid/fields.yaml
    view:
        showSearch: true
        recordsPerPage: 25
        toolbarButtons: bids_toolbar