# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Project

# Model Form Field configuration
form: ~/plugins/ahoy/pyrolancer/models/project/fields_tabs.yaml

# Model Class name
modelClass: Ahoy\Pyrolancer\Models\Project

# Default redirect location
defaultRedirect: ahoy/pyrolancer/projects

# Create page
create:
    title: Create Project
    redirect: ahoy/pyrolancer/projects/preview/:id
    redirectClose: ahoy/pyrolancer/projects

# Update page
update:
    title: Edit Project
    redirect: ahoy/pyrolancer/projects
    redirectClose: ahoy/pyrolancer/projects/preview/:id

# Preview page
preview:
    title: Preview Project
    form: ~/plugins/ahoy/pyrolancer/models/project/fields.yaml